services:
  scrum-poker:
    container_name: scrum-poker
    image: ${IMAGE:-ghcr.io/tommypreel/scrum-poker:latest}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3501:80"
    restart: always
    environment:
      - PORT=80
    networks:
      - web

networks:
  web:
    external: true
    name: web
